sampling:
  - layer: 2
    neighbor: 
      - 10
      - 10
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 32
memory: 
  - type: 'node'
    dim_time: 100
    deliver_to: 'self'
    mail_combine: 'last'
    memory_update: 'ffn'
    mailbox_size: 1
    combine_node_feature: True
    dim_out: 100
gnn:
  - arch: 'DTMP_attention'
    layer: 2
    att_head: 1
    dim_time: 100
    dim_out: 100
train:
  - epoch: 5
    batch_size: 2000
    lr: 0.0001
    dropout: 0.2
    att_dropout: 0.2
    all_on_gpu: False